---
- hosts: no_students
  become: yes
  tasks:

# Setup New User with Sudo and NOPASSWD 

  - name: Download signing keys
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: "{{ item }}"
    with_items:
      - 7638D0442B90D010
      - 8B48AD6246925553
      - 04EE7237B7D453EC
      
  - name: Install basic tools
    apt:
      name: [ git, tcpdump, nmap, aircrack-ng ]
      update_cache: yes
      state: latest
      autoclean: yes
      autoremove: yes